Первая задача на знакомство с Vue
js-tasks-ru/vue-20241213_alexa-4343 pull request #2
Opened 2024-12-18 17:39 UTC by alexandrasm

Решение первой задачи

2024-12-18 17:40 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-19 20:44 UTC, ShGKme requested changes

2024-12-19 20:44 UTC, ShGKme commented on 01-basics/10-create-app/script.js
> +    `
Приложение реализовано в Options API.

Весь курс у нас проходит как на вебинарах, так и в материала - на Composition API. Вы можете решать задачи на Options API и я могу принять это решение, но в некоторых задачах потребуется дорабатывать решение, уже начатое на Composition API, или вообще нельзя будет сделать на чистом Options API.

Напишите, пожалуйста, здесь или в личку, хотите ли решать задачи на Options API

2024-12-20 05:02 UTC, alexandrasm commented on 01-basics/10-create-app/script.js
> +    `
Намерение писать на Composition API

2024-12-21 12:15 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-21 12:59 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @ShGKme

2024-12-21 14:00 UTC, ShGKme approved these changes
Принято

2024-12-21 14:00 UTC, ShGKme commented on 01-basics/20-weather/WeatherApp.js
> +}
Строки в формате `HH:MM` можно сравнивать просто лексикографически как строки без преобразований. `'08:30' < '09:12'`

2024-12-21 14:00 UTC, merged