Решение задачи MeetupView
js-tasks-ru/vue-20241213_alexa-4343 pull request #7
Opened 2024-12-29 15:00 UTC by alexandrasm

2024-12-29 15:01 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-29 16:46 UTC, ShGKme requested changes

2024-12-29 16:46 UTC, ShGKme commented on 03-components/10-MeetupView/MeetupView.js
> +    }
Этот компонент не может нормально функционировать без параметра `meetup`. Он упадёт с `cannot read properties of undefined`. Для упрощения поиска ошибок с ним, нужно явно описывать такие параметры, как обязательные.

2024-12-31 12:19 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-12-31 15:29 UTC, ShGKme approved these changes
С Новым Годом 🎄

2024-12-31 15:30 UTC, merged